//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reniec.ReniecService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReniecService.ServiceDNISoap")]
    public interface ServiceDNISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReniec", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetReniec(string strDNIAuto, string strDNICon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReniec", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetReniecAsync(string strDNIAuto, string strDNICon);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDNISoapChannel : Reniec.ReniecService.ServiceDNISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDNISoapClient : System.ServiceModel.ClientBase<Reniec.ReniecService.ServiceDNISoap>, Reniec.ReniecService.ServiceDNISoap {
        
        public ServiceDNISoapClient() {
        }
        
        public ServiceDNISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDNISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDNISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDNISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetReniec(string strDNIAuto, string strDNICon) {
            return base.Channel.GetReniec(strDNIAuto, strDNICon);
        }
        
        public System.Threading.Tasks.Task<string[]> GetReniecAsync(string strDNIAuto, string strDNICon) {
            return base.Channel.GetReniecAsync(strDNIAuto, strDNICon);
        }
    }
}
