//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reniec.ReniecNewService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReniecNewService.serviciomqSoap")]
    public interface serviciomqSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje obtenerDatosBasicosRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosBasicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reniec.ReniecNewService.obtenerDatosBasicosResponse obtenerDatosBasicos(Reniec.ReniecNewService.obtenerDatosBasicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosBasicos", ReplyAction="*")]
        System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosBasicosResponse> obtenerDatosBasicosAsync(Reniec.ReniecNewService.obtenerDatosBasicosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje obtenerDatosCompletosRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosCompletos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Reniec.ReniecNewService.obtenerDatosCompletosResponse obtenerDatosCompletos(Reniec.ReniecNewService.obtenerDatosCompletosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerDatosCompletos", ReplyAction="*")]
        System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosCompletosResponse> obtenerDatosCompletosAsync(Reniec.ReniecNewService.obtenerDatosCompletosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Credencialmq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appField;
        
        private string usuarioField;
        
        private string claveField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string app {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
                this.RaisePropertyChanged("app");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosBasicos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosBasicosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Reniec.ReniecNewService.Credencialmq Credencialmq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nrodoc;
        
        public obtenerDatosBasicosRequest() {
        }
        
        public obtenerDatosBasicosRequest(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            this.Credencialmq = Credencialmq;
            this.nrodoc = nrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosBasicosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosBasicosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] obtenerDatosBasicosResult;
        
        public obtenerDatosBasicosResponse() {
        }
        
        public obtenerDatosBasicosResponse(string[] obtenerDatosBasicosResult) {
            this.obtenerDatosBasicosResult = obtenerDatosBasicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCompletos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosCompletosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Reniec.ReniecNewService.Credencialmq Credencialmq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nrodoc;
        
        public obtenerDatosCompletosRequest() {
        }
        
        public obtenerDatosCompletosRequest(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            this.Credencialmq = Credencialmq;
            this.nrodoc = nrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDatosCompletosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class obtenerDatosCompletosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] obtenerDatosCompletosResult;
        
        public obtenerDatosCompletosResponse() {
        }
        
        public obtenerDatosCompletosResponse(string[] obtenerDatosCompletosResult) {
            this.obtenerDatosCompletosResult = obtenerDatosCompletosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciomqSoapChannel : Reniec.ReniecNewService.serviciomqSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciomqSoapClient : System.ServiceModel.ClientBase<Reniec.ReniecNewService.serviciomqSoap>, Reniec.ReniecNewService.serviciomqSoap {
        
        public serviciomqSoapClient() {
        }
        
        public serviciomqSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciomqSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciomqSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciomqSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reniec.ReniecNewService.obtenerDatosBasicosResponse Reniec.ReniecNewService.serviciomqSoap.obtenerDatosBasicos(Reniec.ReniecNewService.obtenerDatosBasicosRequest request) {
            return base.Channel.obtenerDatosBasicos(request);
        }
        
        public string[] obtenerDatosBasicos(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            Reniec.ReniecNewService.obtenerDatosBasicosRequest inValue = new Reniec.ReniecNewService.obtenerDatosBasicosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            Reniec.ReniecNewService.obtenerDatosBasicosResponse retVal = ((Reniec.ReniecNewService.serviciomqSoap)(this)).obtenerDatosBasicos(inValue);
            return retVal.obtenerDatosBasicosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosBasicosResponse> Reniec.ReniecNewService.serviciomqSoap.obtenerDatosBasicosAsync(Reniec.ReniecNewService.obtenerDatosBasicosRequest request) {
            return base.Channel.obtenerDatosBasicosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosBasicosResponse> obtenerDatosBasicosAsync(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            Reniec.ReniecNewService.obtenerDatosBasicosRequest inValue = new Reniec.ReniecNewService.obtenerDatosBasicosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            return ((Reniec.ReniecNewService.serviciomqSoap)(this)).obtenerDatosBasicosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Reniec.ReniecNewService.obtenerDatosCompletosResponse Reniec.ReniecNewService.serviciomqSoap.obtenerDatosCompletos(Reniec.ReniecNewService.obtenerDatosCompletosRequest request) {
            return base.Channel.obtenerDatosCompletos(request);
        }
        
        public string[] obtenerDatosCompletos(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            Reniec.ReniecNewService.obtenerDatosCompletosRequest inValue = new Reniec.ReniecNewService.obtenerDatosCompletosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            Reniec.ReniecNewService.obtenerDatosCompletosResponse retVal = ((Reniec.ReniecNewService.serviciomqSoap)(this)).obtenerDatosCompletos(inValue);
            return retVal.obtenerDatosCompletosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosCompletosResponse> Reniec.ReniecNewService.serviciomqSoap.obtenerDatosCompletosAsync(Reniec.ReniecNewService.obtenerDatosCompletosRequest request) {
            return base.Channel.obtenerDatosCompletosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reniec.ReniecNewService.obtenerDatosCompletosResponse> obtenerDatosCompletosAsync(Reniec.ReniecNewService.Credencialmq Credencialmq, string nrodoc) {
            Reniec.ReniecNewService.obtenerDatosCompletosRequest inValue = new Reniec.ReniecNewService.obtenerDatosCompletosRequest();
            inValue.Credencialmq = Credencialmq;
            inValue.nrodoc = nrodoc;
            return ((Reniec.ReniecNewService.serviciomqSoap)(this)).obtenerDatosCompletosAsync(inValue);
        }
    }
}
